### ISSUE TITLE
Any events?

### ISSUE THREAD

**Issue by BobBonser** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#11]
Are there any events I can tap into, such as after the a slide is changed.

I am using this to re-create the effect of sliding tabs like on Android (or iPhone) and need to change the style of a button to show it as the selected slide.

Unless you know of a better way to do this.  I have looked at the Material Design Tabs for Angular 2 but they are still in beta and from what I can see they do not support swiping yet.

**Comment by uzumakinaruto123** [comment]
@BobBonser Why was this closed? Did find any related doc/solution?

**Comment by BobBonser** [comment]
I closed this because I was able to resolve what I needed to do.  In short though, there does not appear to be any events that I could tap into.

**Comment by stubbsy345** [comment]
Having same issue, can you remember how you resolved?
