### ISSUE TITLE
Not working in Android WebView

### ISSUE THREAD

**Issue by BobBonser** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#12]
The swiping works, but it is putting all the swiper-slide contents on the first slide and the next two are blank?

The can be seen at www.wnmobileapps.com/standings/ahl

It looks fine in Chrome on the phone, but when that url is loaded inside an Android Webview, that is when the problem occurs.

**Comment by Luukschoen** [comment]
what about setting an explicit size to the slide?

**Comment by JayChase** [comment]
Hi. Sorry about the delay getting back to you. I don't really have any way of testing in Android WebView. Are you getting any JS errors?

**Comment by Delvezio** [comment]
Set dimension:
swiper{ 
height: 100vh;
width:100vw;
}

**Comment by JayChase** [comment]
Closing based on  Delvezio's response. Please re-open if still an issue.
