### ISSUE TITLE
Setting loop:true adds extra blank slide 

### ISSUE THREAD

**Issue by uzumakinaruto123** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#13]
I have added 3 static slides with option `loop:true`.

**But,** it adds 1 extra blank slide if I do so.

**If,** I do `loop:false` , correct number off slides are created.

**Comment by JayChase** [comment]
Hi. I've had a go at recreating this using the [demo](https://github.com/Useful-Software-Solutions-Ltd/angular2-useful-swiper/blob/master/demo/demo.component.ts). I just get the 3 slides. Can you have a check see if there is anything else I am missing with the config apart from setting **loop: true**.

**Comment by JayChase** [comment]
Closing (see previous).
