### ISSUE TITLE
Feature request: Default image (preloading)

### ISSUE THREAD

**Issue by AnderUstarroz** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#14]
This package is great, I am just missing being able to display preloading or default images until the corresponding images have been completely loaded. 

With the current implementation the images are displayed by chunks, making it look a bit clunky.

**Comment by JayChase** [comment]
Is this feature available with Swiper? If so let me know and I will make sure the API is accessible.

**Comment by AnderUstarroz** [comment]
The feature is available in Swiper,  it's called [lazy loading](http://idangero.us/swiper/demos/30-lazy-load-images.html). Have a look at the [demos](http://idangero.us/swiper/demos/#.WOPp8FOGNE5 ), on section: **Images Lazy Loading**.

**Comment by JayChase** [comment]
Hi, I had a look. This will work without any changes. You can set **lazyLoading** on the config and then set component content as necessary. I tried with [this](https://github.com/nolimits4web/Swiper/blob/master/demos/30-lazy-load-images.html) and it worked ok.
