### ISSUE TITLE
Incompatible with Angular 4

### ISSUE THREAD

**Issue by AnderUstarroz** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#15]
Angular 4 brings [lot of improvements](http://angularjs.blogspot.com.es/2017/03/angular-400-now-available.html). But unfortunately this package doesn't seems to be compatible yet:

    ├──── UNMET PEER DEPENDENCY @angular/core@4.0.0
    └── angular2-useful-swiper@3.0.0

    npm WARN angular2-useful-swiper@3.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.

Is there any change this package will be **compatible with Angular 4** at some stage?

**Comment by AnderUstarroz** [comment]
Seems like  like the new Angular 4 version has backwards compatibility with previous 2.x versions, therefore **latest version of Swiper just work on Angular 4**. Nonetheless it throws a compatibility error, which can be solved  by a simple update of the **package.json**:
```
...
...

  "peerDependencies": {
    "@angular/core": "^2.0.0||^4.0.0"
  },

...
...
```

**Comment by AnderUstarroz** [comment]
In my opinion it is not required but convenient, is better avoiding unnecessary pollution on console. Make your own decision on the matter, but I created the issue because after seen that warning I was assuming that the package probably won't work.  So my guess is that this will just create confusion to other developers.

**Comment by alfupe** [comment]
I was worried of using 
```json
"peerDependencies": {
     "@ Angular / core": "^ 2.0.0 || ^ 4.0.0"
   },
```
but after reading [a bit](https://docs.npmjs.com/files/package.json#peerdependencies) I understand that you were talking to modify this package with this change and not suggesting us to modify our "general" package.json. Sorry!

Thanks a lot @AnderUstarroz.

**Comment by JayChase** [comment]
Hi. I've moved the project to Angular latest and as part of that updated the dependencies. Could you try installing angular2-useful-swiper@4.0.0-alpha.1. If everything is good I will close off the issue.

**Comment by AnderUstarroz** [comment]
I am using Angular Core 4.0.0 and I am getting the following error:

    ├── UNMET PEER DEPENDENCY @angular/compiler@4.0.1
    ├── UNMET PEER DEPENDENCY @angular/core@4.0.1
           └── angular2-useful-swiper@4.0.0-alpha.2  invalid

This is happening because the minimum dependency is **4.0.1** for some libraries on **angular2-useful-swiper/package.json**:

      "@angular/animations": "^4.0.1",
      "@angular/common": "^4.0.1",
      "@angular/compiler": "^4.0.1",
      "@angular/compiler-cli": "^4.0.1",
      "@angular/core": "^4.0.1",
      "@angular/forms": "^4.0.1",
      "@angular/http": "^4.0.1",
      "@angular/material": "^2.0.0-beta.2",
      "@angular/platform-browser": "^4.0.1",
      "@angular/platform-browser-dynamic": "^4.0.1",
      "@angular/router": "^4.0.1",

I think it should be consistent with the angular version defined on **@angular/core**: **^4.0.0 **

**Comment by christophechevalier** [comment]
I use  
```
  "dependencies": {
    "@angular/animations": "4.0.1",
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/flex-layout": "2.0.0-rc.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
...,
    "angular2-useful-swiper": "4.0.1",
    "core-js": "2.4.1",
    "hammerjs": "2.0.8",
...,
    "swiper": "3.4.2",
    "ts-helpers": "1.1.2",
    "underscore": "1.8.3",
    "zone.js": "0.8.5"
  },
```

and I have 0 problem ..
I use Yarn for install all my dependencies. I don't like used " ^ ". Too many problems with that..

**Comment by bpdmax** [comment]
I also had several issues trying to run this in angular 4 (4.1.2) with the error "Swiper is not defined". In my case it was solved just by importing swiper in app.module.ts:

`import 'swiper';`

**Comment by JayChase** [comment]
Closing this off as this repo itself is using Angular 4 as is the demo Plunk .
