### ISSUE TITLE
Problem on the setup

### ISSUE THREAD

**Issue by airjord** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#16]
Dear all,
I hope I can ask a question here, if not I am apologize. 

I have followed all your instruction on the github to add your module into my project.
I am using angular-cli!!
I installed you Module via npm in package into my node_modules

I added the SwiperModule into my app.module.ts

`import { SwiperModule } from '../../node_modules/angular2-useful-swiper/lib/swiper.module';`

and of course
.......
```
imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing,
    SwiperModule
  ],

```
I create a component for the swiper

```
import { Component, OnInit } from '@angular/core';

declare var Swiper: any;

@Component({
  selector: 'app-swiper',
  templateUrl: './swiper.component.html',
  styleUrls: ['./swiper.component.css']
})
export class SwiperComponent implements OnInit {

 config: Object = {
            pagination: '.swiper-pagination',
            paginationClickable: true,
            nextButton: '.swiper-button-next',
            prevButton: '.swiper-button-prev',
            spaceBetween: 30
        };
  
  constructor() { }

  ngOnInit() {
  }

}
```

HTML ......................
```
<swiper [config]="config">
        <div class="swiper-wrapper">
            <div class="swiper-slide">Slide 1</div>
                <div class="swiper-slide">Slide 2</div>
                <div class="swiper-slide">Slide 3</div>
                <div class="swiper-slide">Slide 4</div>
                <div class="swiper-slide">Slide 5</div>
                <div class="swiper-slide">Slide 6</div>
                <div class="swiper-slide">Slide 7</div>
                <div class="swiper-slide">Slide 8</div>
                <div class="swiper-slide">Slide 9</div>
                <div class="swiper-slide">Slide 10</div>
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </swiper>
```

If a call the component I get the following error. 

> 
> error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Error in ./SwiperComponent class SwiperComponent - inline template:0:0 caused by: Swiper is not defined
> Error: Error in ./SwiperComponent class SwiperComponent - inline template:0:0 caused by: Swiper is not defined
>     at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7204:33)
>     at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:30450:16)
>     at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:30515:16)
>     at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:61293:16)
>     at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:83384:23)
>     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:83357:18)
>     at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:83144:18)
>     at CompiledTemplate.proxyViewClass.View_HomeComponent0.detectChangesInternal (/AppModule/HomeComponent/component.ngfactory.js:204:20)
>     at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:83159:14)
>     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:83354:44)
>     at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:83144:18)
>     at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.detectChangesInternal (/AppModule/HomeComponent/host.ngfactory.js:29:19)
>     at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:83159:14)
>     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:83354:44)
>     at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:62220:20)

It makes no sence for me because the module should be there!
Please could you give me a hint. 

Best Regards from germany
Michael

**Comment by JayChase** [comment]
Closing this (see previous comment). Let me know if it needs to be re-opened.
