### ISSUE TITLE
AOT build fails with Property 'containerModifierClass' does not exist on type 'Object'.

### ISSUE THREAD

**Issue by viljark** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#17]
Hello!

I upgraded to the latest version & after this my AOT build fails with:
`aot/node_modules/angular2-useful-swiper/lib/swiper.component.ngfactory.ts (1,1): Property 'containerModifierClass' does not exist on type 'Object'.
`

**Comment by JayChase** [comment]
Sorry about that changed config from object to any.

**Comment by viljark** [comment]
Cheers, thanks for quick fix!
