### ISSUE TITLE
Thumbs gallery support

### ISSUE THREAD

**Issue by vforvasquez** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#19]
Are there any plans for enabling this version to do something like the [thumbs gallery](https://github.com/nolimits4web/Swiper/blob/master/demos/23-thumbs-gallery.html#L76) ?

**Comment by aperalta02** [comment]
I'm interested in this feature too, will be implemented?

**Comment by JayChase** [comment]
You can do that already. I made a demo plunk here: http://embed.plnkr.co/L0CEkF/

**Comment by MatthewTeolis** [comment]
The plunk demo doesn't work. Did the API break it ?

**Comment by JayChase** [comment]
Your right. It's fixed now.

**Comment by saadmomin** [comment]
I need this. PLunkr not working. Please help
