### ISSUE TITLE
AoT Compiler Error

### ISSUE THREAD

**Issue by irvjc82** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#2]
When I try to compile my Angular-Cli projet it throws the error below:

 0% compilingUnexpected value 'SwiperModule' imported by the module 'AppModule'
Error: Unexpected value 'SwiperModule' imported by the module 'AppModule'...

I am not sure what is wrong.

Thanks in advance for any help you are able to provide!

**Comment by JayChase** [comment]
This package should be ok for AoT if angular-cli is on the latest version 1.0.0-beta.18, I don't think it will work with earlier versions. If you are on that version could you share a copy of the project with me so I can see what is going wrong?

**Comment by JayChase** [comment]
It looks like I am going to have to make some changes to my build to make this AoT friendly https://medium.com/@mohuk/publishing-aot-compliant-angular-2-packages-eb188ab5635#.6b5echl9o. I'll start doing some testing but it might take a week or so before I have a release ready.

**Comment by JayChase** [comment]
Can you try with angular2-useful-swiper@3.0.0-alpha.2 and see if everything works now? The module is now being built with ngc which produces the metadata needed for AoT.

**Comment by irvjc82** [comment]
Thanks i'll give it a try and let you know how it works.

**Comment by irvjc82** [comment]
It´s working now. Thanks!

**Comment by JayChase** [comment]
Excellent. I've moved it to a proper release.
