### ISSUE TITLE
Error: BrowserModule has already been loaded

### ISSUE THREAD

**Issue by tahuyhien** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#4]
Hi JayChase,
 
I am using lazy loaded to load module then I am getting below error when run app : 

Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

I find out that you imported BrowserModule in SwiperModule. I think BrowserModule  should import once in rootModule and other modules just import CommonModule.

Please help me to review and correct me if anything wrong.

Thanks

**Comment by JayChase** [comment]
Thanks for spotting that, I've removed the import in angular2-useful-swiper@3.0.0-alpha.2. I will do a full release once I've finished testing.
