### ISSUE TITLE
ReferenceError: Swiper is not defined

### ISSUE THREAD

**Issue by yelenka** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#5]
I have installed the package, added it to the SystemJs  file. 
Added all DI to the app.module.ts.
And got the error 
ReferenceError: Swiper is not defined
    at SwiperComponent.setup (http://localhost:30814/lib/angular2-useful-swiper/lib/swiper.component.js)

What's the problem?
Thanks

**Comment by JayChase** [comment]
It looks like swiper is not getting loaded. Have you added the swiper.js ref to your index.html?

**Comment by yelenka** [comment]
sorry i have added not to the correct index.html. It works fine,
Thank you!

**Comment by christophechevalier** [comment]
You need to install swiper and add the path to angular-cli.json like that : 

`
      "styles": [  
...,  
        "../node_modules/swiper/dist/css/swiper.min.css",  
        "styles.scss"  
      ],  
      "scripts": [  
...,  
        "../node_modules/swiper/dist/js/swiper.min.js"  
      ],  
`

Please, could you update your readme. Thanks :eagle:
