### ISSUE TITLE
Reference to call API

### ISSUE THREAD

**Issue by duytrantps** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#6]
Is there any way to reference the swiper element to call its API in angular 2

**Comment by JayChase** [comment]
There is a Swiper property on the component which gets set to the instance of Swiper returned when it is initialized. You can get to it by creating a template reference like below:

`<swiper [config]="config" #usefulSwiper>`

You can then use the reference to get to the Swiper (but it can be undefined before it has been initialiazed so be sure to check for that).

`<button (click)="usefulSwiper.Swiper.createLoop()">loop it</button>`
