### ISSUE TITLE
get reference to slider

### ISSUE THREAD

**Issue by alfupe** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#7]
Thanks @JayChase for this

I need to do a slide change using slideTo:
(from the documentation: http://idangero.us/swiper/api/)
mySwiper.slideTo(index, speed, runCallbacks);

But I have no idea how to get reference to (in this case "mySwiper"

Could you help me please?
Thanks,
Alex

**Comment by JayChase** [comment]
There is a Swiper property on the component which gets set to the instance of Swiper returned when it is initialized. You can get to it by creating a template reference like below:

`<swiper [config]="config" #usefulSwiper>`

You can then use the reference to get to the Swiper (but it can be undefined before it has been initialiazed so be sure to check for that). For instance:

`<button (click)="usefulSwiper.Swiper.createLoop()">loop it</button>`

**Comment by alfupe** [comment]
Thanks a lot!

I didn't see that this was already answered in another closed issue, sorry.

**Comment by JayChase** [comment]
No problem. I'll get it added to the readme too.

**Comment by Sureshee** [comment]
Hi can you help me in updating on how this can be called from typescript, especially for sliding next. I couldn't able to succeed.
