### ISSUE TITLE
Angular-cli change

### ISSUE THREAD

**Issue by dakipro** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#8]
Hi,
first i must say thank you for this library, it is the best one for ang2 out there.
I installed it in the angular-cli version, and I didn't had to change the "packages" section of the JSON, however I had to add .js files to the "scripts" and "styles" section of the JSON.
Something like
`
"styles": [
        "../node_modules/swiper/dist/css/swiper.min.css",
        ...
"scripts": [
        "../node_modules/swiper/dist/js/swiper.min.js",
       ....
`

**Comment by JayChase** [comment]
Good to hear that, thank you. I think essentially the packages and scripts sections are doing the same thing in terms of making sure that the module gets bundled up. If you use packages though ng will handle the individual scripts.
