### ISSUE TITLE
Custom container and wrapper classes

### ISSUE THREAD

**Issue by simkepal** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#9]
Hello,

great work with this. I have a question: Is it possible to change the code so user can have custom swiper-container and swiper-wrapper classes? As I can see, the original swiper has this options. If you are to buisy I can help you with that.

Thank you

**Comment by JayChase** [comment]
Hi. Is this is a config option? You should be able to set any API options with the config object. If not let me know more and we can get the changes made.

**Comment by simkepal** [comment]
Thank you for your response. Yes, this are config options and are working on all classes now, except on swiper-container and swiper-wrapper. This is because you have hard coded this classes in your code. It would be great to use classes from options if there are set.

**Comment by DavidLevayer** [comment]
Hello!

Thanks for your work on this, the component is efficient and ready-to-use. I'm facing the same problem as simkepal: I'd like to customize `swiper-container` class but I can't (because swiper is an external component and I can't update its CSS).

Any feedback on this would be appreciated!

**Comment by JayChase** [comment]
Which options are you trying to set? I'm trying to think of a way of doing this which will still allow the easy set up using the defaults.

**Comment by simkepal** [comment]
I would like to set containerModifierClass and wrapperClass. I want to have classes set based on BEM metodology (https://en.bem.info/methodology/quick-start/).

**Comment by DavidLevayer** [comment]
@krjordan Thanks! The `/deep/` works perfectly for my issue.

**Comment by JayChase** [comment]
Hi. I know this has been ages but I am working on a new release for Angular 4 and as part of it I have made the **swiper-container** class only be set on the condition **config.containerModifierClass** not being set/ Can you let me know whether **angular2-useful-swiper@latest** fixes this issue?

**Comment by JayChase** [comment]
Closing (see previous).
